services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: note
      POSTGRES_USER: note
      POSTGRES_PASSWORD: note
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
